manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: flake-zmk-module
      url-base: https://github.com/anywhy-io
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: anywhy_flake
      remote: flake-zmk-module
      revision: main
      import: west.yml
  self:
    path: config
